services:
  - type: web
    name: symmetrich-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDBzzDe1fq7mjPKZTMhbNzC3DGqe-EW3_E